services:
  - type: web
    name: ai-bike-router
    env: python
    plan: free
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ORS_API_KEY
        sync: false
